// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVN6dAxOiPxDQ-nhgdurzSxQDzAehAlZM',
    appId: '1:362813191635:web:184ee3040aab319750eb26',
    messagingSenderId: '362813191635',
    projectId: 'emergency-alert-system-e0a91',
    authDomain: 'emergency-alert-system-e0a91.firebaseapp.com',
    storageBucket: 'emergency-alert-system-e0a91.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX', // Replace with your measurementId if any
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVN6dAxOiPxDQ-nhgdurzSxQDzAehAlZM',
    appId: '1:362813191635:android:184ee3040aab319750eb26',
    messagingSenderId: '362813191635',
    projectId: 'emergency-alert-system-e0a91',
    storageBucket: 'emergency-alert-system-e0a91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVN6dAxOiPxDQ-nhgdurzSxQDzAehAlZM',
    appId:
        '1:362813191635:ios:YOUR_IOS_APP_ID', // Update with correct iOS app id
    messagingSenderId: '362813191635',
    projectId: 'emergency-alert-system-e0a91',
    storageBucket: 'emergency-alert-system-e0a91.firebasestorage.app',
    iosBundleId: 'com.example.emergencyAlertApp',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVN6dAxOiPxDQ-nhgdurzSxQDzAehAlZM',
    appId: '1:362813191635:web:YOUR_WINDOWS_APP_ID', // Update if needed
    messagingSenderId: '362813191635',
    projectId: 'emergency-alert-system-e0a91',
    authDomain: 'emergency-alert-system-e0a91.firebaseapp.com',
    storageBucket: 'emergency-alert-system-e0a91.firebasestorage.app',
  );
}
